[Feat] IOS 호흡 세션 MindfulSession 연동 저장
DeveloperAcademy-POSTECH/2024-MacC-A7-92NMS pull request #62
Opened 2024-11-23 18:29 UTC by seoyeon-choo

## 🔥 작업한 내용

- **BreathingOutroView 구현**
  - `BreathingOutroView`를 추가하여 종료 화면의 애니메이션 및 데이터 기록을 담당하도록 구현
  - 뷰와 로직 분리를 위해 `BreathingOutroViewModel`으로 분리

- **MindfulSession 기록 로직 추가**
  - `MindfulSessionManager`를 활용하여 테스트 세션 데이터를 HealthKit에 기록하는 기능 구현
  - `recordTestMindfulSession` 메서드를 통해 세션 기록

## ⭐️ PR Point
- 뷰와 로직을 분리하여 `BreathingOutroViewModel`에서 애니메이션 및 데이터 기록 로직을 관리하도록 개선했습니다.

## 🔧 TODO
- **HealthKit 데이터 저장 기능 검증**
  - HealthKit 데이터를 저장하는 기능의 성공 여부를 watchOS에서도 테스트할 필요가 있습니다.
  - watchOS 데이터 저장을 위한 권한 요청

## 🚨 관련 이슈
- Resolved: #56

2024-11-23 18:57 UTC, VronzeWook approved these changes
LGTM

2024-11-24 08:09 UTC, jiyoungsophia reviewed
recordTestMindfulSession에서 호흡 운동한 시간 설정 수정이 필요해보입니다!

2024-11-24 08:09 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
메모리 누수 방지를 위해 [weak self] 사용을 고려해보면 좋을 것 같아요!

2024-11-24 08:09 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +            DispatchQueue.main.async {
여기도 동일하게 [weak self] 사용을 고려해보면 좋을 것 같아요!

2024-11-24 08:09 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +        let endDate = Calendar.current.date(byAdding: .minute, value: 10, to: startDate)!
이렇게 되면 호흡한 시간이 10분으로 저장되는 것이지 않나요?! 임시 코드인걸까요??
시작시간을 호흡이 끝난 시점으로 한 이유도 궁금합니다!

2024-11-24 08:14 UTC, jiyoungsophia requested changes

2024-11-24 08:14 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +            withAnimation(.easeOut(duration: 1.0)) {
메모리 누수 방지를 위해 [Weak self] 사용을 고려해보면 좋을 것 같아요!

2024-11-24 08:14 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +        let endDate = Calendar.current.date(byAdding: .minute, value: 10, to: startDate)!
이렇게 되면 호흡한 시간이 10분으로 저장되는 것이지 않나요?! 임시 코드인걸까요??
시작시간을 호흡이 끝난 시점으로 한 이유도 궁금합니다!

2024-11-24 08:14 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +                if success {
여기도 동일하게 [weak self] 사용을 고려해보면 좋을 것 같아요!

2024-11-24 14:42 UTC, seoyeon-choo commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +                if success {
수정 반영했습니다

2024-11-24 14:42 UTC, seoyeon-choo commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +        let endDate = Calendar.current.date(byAdding: .minute, value: 10, to: startDate)!
수정 반영했습니다

2024-11-24 14:42 UTC, seoyeon-choo commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +            withAnimation(.easeOut(duration: 1.0)) {
수정 반영했습니다

2024-11-25 01:39 UTC, jiyoungsophia commented on Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
> +        let endDate = Calendar.current.date(byAdding: .minute, value: 10, to: startDate)!
추후에 호흡 시간 관리는 매니저로 빼서 관리하도록 리팩토링하면 좋을 것 같아요!

2024-11-25 01:40 UTC, jiyoungsophia approved these changes
빠른 수정 최고~~!

2024-11-25 02:36 UTC, merged