Feat/#54 watch breathing outro view mind session data
DeveloperAcademy-POSTECH/2024-MacC-A7-92NMS pull request #63
Opened 2024-11-23 21:45 UTC by seoyeon-choo

## 🔥 작업한 내용
- **WatchBreathingOutroView 구현**
  - `WatchBreathingOutroView`를 추가하여 종료 화면의 애니메이션 및 데이터 기록을 담당하도록 구현
  - 뷰와 로직 분리를 위해 `WatchBreathingOutroViewModel`으로 분리

- **MindfulSession 기록 로직 추가**
  - `MindfulSessionManager`를 활용하여 테스트 세션 데이터를 HealthKit에 기록하는 기능 구현
  - `recordTestMindfulSession` 메서드를 통해 세션 기록

## ⭐️ PR Point
- 뷰와 로직을 분리하여 `WatchBreathingOutroViewModel`에서 애니메이션 및 데이터 기록 로직을 관리하도록 개선했습니다.

## 🔧 TODO
- WatchOS HRV 기록시 Notification 전송 후  BreathingSession 연결

## 🚨 관련 이슈
- Resolved: #54

2024-11-24 08:20 UTC, jiyoungsophia requested changes
이전 pr과 동일한 이슈가 있습니다! 특히 메모리 관련 이슈는 워치에서 더욱 중요할수 있어 수정이 필요해보입니다!

2024-11-24 08:20 UTC, jiyoungsophia commented on Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroViewModel.swift
> +                if success {
[weak self] 사용해 메모리 누수 방지가 필요해보입니다

2024-11-24 08:20 UTC, jiyoungsophia commented on Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroViewModel.swift
> +        let endDate = Calendar.current.date(byAdding: .minute, value: 10, to: startDate)!
실제 호흡 운동시간을 정확하게 할 필요가 있어보입니다

2024-11-24 14:46 UTC, seoyeon-choo commented on Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroViewModel.swift
> +                if success {
수정반영했습니다!

2024-11-24 14:46 UTC, seoyeon-choo commented on Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroViewModel.swift
> +        let endDate = Calendar.current.date(byAdding: .minute, value: 10, to: startDate)!
수정반영했습니다!

2024-11-25 05:37 UTC, jiyoungsophia approved these changes
세이디 최고~!!!!!

2024-11-25 05:47 UTC, VronzeWook approved these changes
weak self 적용 좋은 포인트 같아용

2024-11-25 06:02 UTC, merged