Feat/#2 health kit fetch hrv
DeveloperAcademy-POSTECH/2024-MacC-A7-92NMS pull request #7
Opened 2024-11-13 08:44 UTC by VronzeWook

## 🔥 작업한 내용
- HealthKit Manager Interface 작성
- HealthKit Manager에 HealthKit 권한 요청 메서드 구현
- HealthStore 접근 권한을 위한 info-plist 작성
- 빌드 중 WKCompanionAppBundleIdentifier(watchOS info-plist 중)가 앱의 bundleID와 불일치하여 수정
- 최소 타겟을 iOS 17.2, watchOS 10.2로 수정
- visionOS, macOS, 화면 전환 설정 제거
- HealthManager에 fetchDailyHRV 메서드 구현
- HealthManager에 fetchMonthlyHRV 메서드 구현
- Daily, Monthly HRV data fetch를 테스트하기 위한 TestView 구현
- SphaApp에서 HealthStore 권한 요청

## ⭐️ PR Point

- 현재 앱 진입까지 대기 시간이 꽤 소요됩니다.
- 만약 이 원인이 HealthStore에 권한을 요청하는 메서드가 매번 실행되어 그렇다면 한번 권한을 허용 받은 후에는 스킵할 수 있도록 구현이 필요해보입니다. 다만 추측에 그치는 것으로, 추후 로딩시간 개선 작업이 필요해보입니다.
- 타겟 같은 경우 큰 이유보다 주로 많이 사용하는 타겟으로 설정되어 변경이 필요하다면 말씀해주세요.

## 📸 스크린샷

https://github.com/user-attachments/assets/6d6e48b4-ca13-4bee-8022-#2 9a854c978b1

## 🚨 관련 이슈
- Resolved: #2

2024-11-13 08:44 UTC, jiyoungsophia commented
제목 수정해주세요

2024-11-13 12:41 UTC, seoyeon-choo requested changes
수고하셨습니다! 컨플릭만 해결해주세요!

2024-11-13 13:03 UTC, jiyoungsophia requested changes
컨플릭트와 코멘트 확인해주세요! 고생하셨습니다!

2024-11-13 13:03 UTC, jiyoungsophia commented on Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
> +         }
해당 메서드의 목적이 월별 통계에 뿌려줄 데이터라면 `HKStatisticsCollectionQuery` 에 대한 고려도 필요해보입니다

2024-11-13 16:52 UTC, VronzeWook commented on Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
> +}
private으로 해보려다가 수정하는 과정에서 빠뜨렸네요. 수정하겠습니다 !

2024-11-13 16:53 UTC, VronzeWook commented on Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
> +extension HealthKitManager {
큰 의미는 없고 단순히 HealthKitManager에 메서드들을 유형별로 분류해서 가독성을 높이려고 했습니다!

2024-11-13 16:53 UTC, VronzeWook commented on Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
> +         }
네 좋은 지적인거 같습니다. 다음 번에 개선해서 반영하도록 하겠습니다.

2024-11-14 01:31 UTC, jiyoungsophia approved these changes

2024-11-14 05:08 UTC, seoyeon-choo approved these changes

2024-11-14 05:12 UTC, merged